# nixpacks.toml (الصيغة الصحيحة)

[phases.setup]
# نحدد حزم Nix التي نحتاجها. nodejs_20 هو إصدار مستقر وحديث.
nixPkgs = ["nodejs_20"]

[phases.install]
# أمر تثبيت الاعتماديات. استخدام npm ci أفضل للخوادم لأنه أسرع ويستخدم package-lock.json.
command = "npm ci"

[phases.build]
# أمر بناء المشروع من ملف package.json
command = "npm run build"

[start]
# أمر بدء تشغيل الخادم من ملف package.json
command = "npm start"
